from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from archapi.frameworks.generic import GenericAdapter
from archapi.types import APIPlan, APIGenome, GeneratedFile, ScanResult, ValidationReport


class DjangoDRFAdapter(GenericAdapter):
    """
    Framework adapter for Django REST Framework (Python).

    Generates ViewSet-based views, serializers, URL configuration, and pytest-django
    tests that match DRF conventions.
    """

    name = "django-drf"

    # ------------------------------------------------------------------
    # Scan / genome
    # ------------------------------------------------------------------

    def scan(self, project_path: Path) -> ScanResult:
        result = super().scan(project_path)
        result.framework = self.name
        return result

    def extract_genome(self, maps: Dict[str, Any], scan_result: ScanResult) -> APIGenome:
        genome = super().extract_genome(maps, scan_result)
        genome.framework = self.name

        dep_text = self._dep_text(scan_result.project_path)

        has_drf = "djangorestframework" in dep_text or "rest_framework" in dep_text
        has_django = "django" in dep_text

        # ViewSet vs APIView detection: prefer ViewSet if models found
        genome.route_style = "drf-router" if scan_result.routes else "unknown"
        genome.controller_style = (
            "drf-viewset" if scan_result.models else
            ("drf-apiview" if scan_result.controllers or scan_result.routes else "unknown")
        )
        genome.service_style = "service-layer" if scan_result.services else "unknown"
        genome.schema_style = "drf-serializer" if (has_drf or scan_result.schemas) else "unknown"
        genome.test_style = "pytest-django" if ("pytest" in dep_text or scan_result.tests) else "unknown"
        genome.metadata["language"] = "python"
        genome.metadata["project_path"] = str(scan_result.project_path)

        if not has_django:
            genome.confidence = min(genome.confidence, 0.35)
            genome.metadata["dependency_warning"] = "Django dependency not found."
        elif not has_drf:
            genome.confidence = min(genome.confidence, 0.55)
            genome.metadata["dependency_warning"] = "djangorestframework not found — DRF may not be in use."

        return genome

    # ------------------------------------------------------------------
    # Code generation
    # ------------------------------------------------------------------

    def generate_code(
        self,
        plan: APIPlan,
        genome: APIGenome,
        maps: Dict[str, Any],
    ) -> List[GeneratedFile]:
        if not plan.generation_allowed:
            return []

        entity = plan.entities[-1] if plan.entities else "Resource"
        entity_pascal = entity[0].upper() + entity[1:]
        entity_lower = entity_pascal[0].lower() + entity_pascal[1:]
        entity_file = entity_lower.lower()

        # Detect the app directory from existing routes / views
        app_dir = self._detect_app_dir(maps)

        views_path = app_dir / "views.py"
        serializers_path = app_dir / "serializers.py"
        urls_path = app_dir / "urls.py"
        test_path = Path("tests") / f"test_{entity_file}.py"

        method = plan.method  # GET / POST / PUT / DELETE / PATCH
        http_path = plan.path
        action = plan.metadata.get("action", "unknown")
        status_code = int(plan.metadata.get("response_status", 200))

        viewset_style = genome.controller_style == "drf-viewset"

        # ------------------------------------------------------------------
        # views.py
        # ------------------------------------------------------------------
        if viewset_style:
            views_content = f'''from rest_framework import viewsets, status
from rest_framework.response import Response
from .serializers import {entity_pascal}Serializer


class {entity_pascal}ViewSet(viewsets.ViewSet):
    """
    ViewSet for {entity_pascal} — generated by ArchAPI.
    """

    def list(self, request):
        # TODO: Replace with real queryset logic.
        return Response(
            {{"message": "{entity_pascal} list placeholder", "action": "{action}"}},
            status=status.HTTP_200_OK,
        )

    def create(self, request):
        serializer = {entity_pascal}Serializer(data=request.data)
        if serializer.is_valid():
            # TODO: Persist the object here.
            return Response(serializer.validated_data, status=status.HTTP_{status_code}_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def retrieve(self, request, pk=None):
        return Response(
            {{"message": "{entity_pascal} detail placeholder", "pk": pk}},
            status=status.HTTP_200_OK,
        )
'''
        else:
            # APIView style
            views_content = f'''from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import {entity_pascal}Serializer


class {entity_pascal}View(APIView):
    """
    APIView for {entity_pascal} — generated by ArchAPI.
    """

    def {method.lower()}(self, request, *args, **kwargs):
        # TODO: Replace this placeholder with project-specific business logic.
        return Response(
            {{"message": "{entity_pascal} API placeholder response", "action": "{action}"}},
            status=status.HTTP_{status_code}_OK if {status_code} == 200 else status.HTTP_{status_code}_CREATED,
        )
'''

        # ------------------------------------------------------------------
        # serializers.py
        # ------------------------------------------------------------------
        serializers_content = f'''from rest_framework import serializers


class {entity_pascal}Serializer(serializers.Serializer):
    message = serializers.CharField(default="{entity_pascal} response")
    action = serializers.CharField(default="{action}")
    # TODO: Add project-specific fields here.
'''

        # ------------------------------------------------------------------
        # urls.py
        # ------------------------------------------------------------------
        if viewset_style:
            urls_content = f'''from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import {entity_pascal}ViewSet

router = DefaultRouter()
router.register(r"{entity_file}s", {entity_pascal}ViewSet, basename="{entity_file}")

urlpatterns = [
    path("", include(router.urls)),
]
'''
        else:
            urls_content = f'''from django.urls import path
from .views import {entity_pascal}View

urlpatterns = [
    path("{http_path.lstrip("/")}", {entity_pascal}View.as_view(), name="{entity_file}-api"),
]
'''

        # ------------------------------------------------------------------
        # tests/test_<entity>.py
        # ------------------------------------------------------------------
        test_content = f'''import pytest


@pytest.mark.django_db
def test_{entity_lower}_placeholder(client):
    # TODO: Replace this placeholder with a real API test.
    assert True
'''

        return [
            GeneratedFile(views_path, views_content),
            GeneratedFile(serializers_path, serializers_content),
            GeneratedFile(urls_path, urls_content),
            GeneratedFile(test_path, test_content),
        ]

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate_generated_code(
        self,
        files: List[GeneratedFile],
        plan: APIPlan,
        genome: APIGenome,
    ) -> ValidationReport:
        errors: List[str] = []
        warnings: List[str] = []

        if not plan.generation_allowed:
            errors.append(plan.reason or "Generation not allowed.")

        required_names = ["views.py", "serializers.py", "urls.py"]
        generated_names = [Path(file.path).name for file in files]

        for name in required_names:
            if name not in generated_names:
                errors.append(f"Missing generated DRF layer: {name}")

        if not any("test_" in Path(file.path).name for file in files):
            errors.append("Missing generated DRF test layer.")

        for file in files:
            if not file.content.strip():
                errors.append(f"Generated file is empty: {file.path}")
            if Path(file.path).exists():
                warnings.append(
                    f"Generated file path already exists relative to current directory: {file.path}"
                )

        if genome.confidence < 0.75:
            warnings.append("Architecture confidence is moderate; review generated files before applying.")

        return ValidationReport(success=not errors, errors=errors, warnings=warnings)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _dep_text(self, project_path: Path) -> str:
        text = ""
        for fname in ("requirements.txt", "pyproject.toml", "setup.cfg", "Pipfile"):
            p = project_path / fname
            if p.exists():
                text += p.read_text(encoding="utf-8", errors="ignore").lower()
        return text

    def _detect_app_dir(self, maps: Dict[str, Any]) -> Path:
        """Infer the primary app directory from the route/controller/service maps."""
        for map_key in ("route_map", "controller_map", "service_map"):
            values = maps.get(map_key, {})
            project_path = Path(maps.get("_project_path", "."))
            if isinstance(values, dict) and values:
                first_path = Path(next(iter(values.values()))).resolve()
                parent = first_path.parent
                try:
                    return parent.relative_to(project_path)
                except ValueError:
                    pass
        return Path("api")  # sensible DRF default
